bot:
  token: ${BOT_TOKEN}

spring:
  datasource:
    url: jdbc:h2:mem:telegram_user
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect