bot:
  token: ${BOT_TOKEN}
  update:
    rate: 3600000 # An hour
    initial-delay: 600000 # 10 minutes

spring:
  datasource:
    url: jdbc:h2:mem:telegram_user
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: telegramUser:com.system205.entity.TelegramUser

    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

